### ISSUE TITLE
Add a 20.04 variant of the image

### ISSUE THREAD

**Issue by mattrayner** [mattrayner/docker-lamp#102]
Now that there is a LTS 20.04 release, we should add a 20.04 variant of the image

**Comment by pzhlkj6612** [comment]
Waiting for [phusion/baseimage-docker](https://github.com/phusion/baseimage-docker/releases) to release a stable 20.04 image...

**Comment by pzhlkj6612** [comment]
OK, it comes: https://github.com/phusion/baseimage-docker/releases/tag/focal-1.0.0

**Comment by mattrayner** [comment]
This was fixed by #123
