### ISSUE TITLE
Cant use variable in mysqli_query()

### ISSUE THREAD

**Issue by ahmad-shiddiq** [mattrayner/docker-lamp#110]
I have an issue with this, when I use docker to create some record into the database I can't do that. Here code what I mean.
```php
$query = mysqli_query($connection, "INSERT INTO users VALUES(NULL, '$name', '$email', '$phone')");
```

I have tried with Xampp, and I didn't found the issues. Which means I think something wrong with docker lamp.

**Comment by freakpants** [comment]
What's the error message you're getting?

**Comment by ahmad-shiddiq** [comment]
Sorry, I forget to send the log here. And now I just installed that.
I will close this issue now.
