### ISSUE TITLE
Persisting your MySQL - Would need it INSIDE the docker Image

### ISSUE THREAD

**Issue by smalldragoon** [mattrayner/docker-lamp#114]
Hi all, 
To follow-up on my previous questions  on location of the project, I would need now to have /mysql INSIDE the docker image instead of stored outside.
So, to loop on previous posts and discussion, yes I know it is not the Docker philosophy but seems that my users have 2 left hands if not no arms at all ;-).
So, to solve actual and potentially any further issues, I would like to store everything in the container ( ie : like a virtual machine that you launch exposing some ports ) 
Having explained that, I tried to do some tests but so far, each time I relaunch the image, it recreates from scratch the DB. How could I do my need ? 
thanks !

**Comment by mattrayner** [comment]
Hi smaldragon,
 I don't think you can persist the information like you are thinking where everything is inside the container to be reused every time. However, you can use names volumes which may give you what you are after?

https://www.altaro.com/msp-dojo/persistent-docker-containers/

Thanks,
Matt
