### ISSUE TITLE
Docker Lamp redirect https

### ISSUE THREAD

**Issue by giammo** [mattrayner/docker-lamp#115]
I'm new to dockers. I installed docker lamp (mattrayner/lamp).

I put my project in /var/www/html and when I browse the project I am always redirected to https.

The problem is that with https localhost it gives me an error. With http, however, the project works.

Can anyone give me some suggestions?

Thank you all for your availability.

**Comment by pzhlkj6612** [comment]
Hi.

> when I browse the project I am always redirected to https.

I guess some of your browser settings are wrong. Here is a related question: [How to stop an automatic redirect from “http://” to “https://” in Chrome - Super User](https://superuser.com/questions/565409/how-to-stop-an-automatic-redirect-from-http-to-https-in-chrome) . I hope this will help.

**Comment by mattrayner** [comment]
Hi @giammo I am comfortable that this is not a docker image specific issue and likely to be a browser problem as noted by @pzhlkj6612 so will be closing this issue. If you are still having issues or disagree, please let me know

Thanks,
Matt
