### ISSUE TITLE
PHP 8 will be installed on Ubuntu 18.04

### ISSUE THREAD

**Issue by pzhlkj6612** [mattrayner/docker-lamp#122]
We can get the following error from the [latest test](https://app.circleci.com/pipelines/github/mattrayner/docker-lamp/35/workflows/66a344f5-257c-42e6-bf0b-6bc3fcab3d36/jobs/193):

```
=> Checking against expected values (1804-php7)
...
< PHP Version: 8.0.10<br/>
---
...
> PHP Version: 7.4.8<br/>
=> Failed
make: *** [run-tests] Error 1
```

Ondřej Surý has released [PHP 8](https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=php8) for 18.04 on [ppa:ondrej/php](https://launchpad.net/~ondrej/+archive/ubuntu/php), but we need PHP 7.4 and [it still exists](https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=php7.4). Maybe we need to specify the package version in the `apt-get` command.

**Comment by mattrayner** [comment]
This appears to have been fixed with the merging of #123. I will monitor and re-open if I am still seeing it :)
