### ISSUE TITLE
"apache2 entered FATAL state, too many start retries too quickly"

### ISSUE THREAD

**Issue by kjlhgfds** [mattrayner/docker-lamp#137]
Hello there,
I'm on Linux Mint and sometimes, when the container starts (when I start my computer), it doesn't stay up (sometimes it works perfectly). I tried restarting the container, restarting the computer : most of the times it doesn't work.

Here is the code I use :
```
docker run -i -t 
--name blabla 
-p 83:80 
-v /mnt/blabla/app:/app 
-v /mnt/blabla/mysql:/var/lib/mysql 
--restart always 
mattrayner/lamp:latest
```

Here is the log in Portainer :
```
Updating for PHP 8.0
Replacing CLI php.ini values
Editing APACHE_RUN_GROUP environment variable
Editing phpmyadmin config
Setting up MySQL directories
Allowing Apache/PHP to write to the app
Allowing Apache/PHP to write to MySQL
Removing MySQL socket
Editing MySQL config
=> Using an existing volume of MySQL
Starting supervisord
/usr/local/lib/python3.8/dist-packages/supervisor-4.2.2-py3.8.egg/supervisor/options.py:474: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  self.warnings.warn(
2023-11-02 06:21:21,540 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2023-11-02 06:21:21,540 INFO Included extra file "/etc/supervisor/conf.d/supervisord-apache2.conf" during parsing
2023-11-02 06:21:21,540 INFO Included extra file "/etc/supervisor/conf.d/supervisord-mysqld.conf" during parsing
Unlinking stale socket /var/run/supervisor.sock
2023-11-02 06:21:21,843 INFO RPC interface 'supervisor' initialized
2023-11-02 06:21:21,843 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-11-02 06:21:21,844 INFO supervisord started with pid 1
2023-11-02 06:21:22,845 INFO spawned: 'apache2' with pid 29
2023-11-02 06:21:22,846 INFO spawned: 'mysqld' with pid 30
2023-11-02 06:21:22,889 INFO exited: apache2 (exit status 0; not expected)
2023-11-02 06:21:23,993 INFO spawned: 'apache2' with pid 201
2023-11-02 06:21:23,993 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2023-11-02 06:21:24,028 INFO exited: apache2 (exit status 0; not expected)
2023-11-02 06:21:26,031 INFO spawned: 'apache2' with pid 226
2023-11-02 06:21:26,090 INFO exited: apache2 (exit status 0; not expected)
2023-11-02 06:21:29,093 INFO spawned: 'apache2' with pid 227
2023-11-02 06:21:29,134 INFO exited: apache2 (exit status 0; not expected)
2023-11-02 06:21:30,136 INFO gave up: apache2 entered FATAL state, too many start retries too quickly
```

What is the problem and what can I do to fix it ?
Tell me if you need any more information.

Thanks !

**Comment by pzhlkj6612** [comment]
Hi!

It looks like Apache is dead. I think you may be able to find the problem by manually launching Apache. Enter your container and execute "`source /etc/apache2/envvars && apache2`" to see what happens.

FWIW, Apache is launched by [supervisor](https://pypi.org/project/supervisor/) with the config file "supporting_files/supervisord-apache2.conf".

**Comment by kjlhgfds** [comment]
I entered the container with
`docker exec -it blabla /bin/bash`
and executed
`source /etc/apache2/envvars && apache2`
The answer was
`httpd (pid 30) already running`

I understand that "mysqld" is running but not "apache2" (?).

**Comment by pzhlkj6612** [comment]
> EDIT : I saw that in the launch command, the versioning is now `mattrayner/lamp:latest-2004-php8` and not `mattrayner/lamp:latest`.

Interesting. The digest of `mattrayner/lamp:latest` is [f7caeba589ea](https://hub.docker.com/layers/mattrayner/lamp/latest/images/sha256-f7caeba589eaea7e3d20f4ae3e3bf88233e66e7df59eb5adb49161a5365f9f90?context=explore). [`build-210-2004-php8`](https://hub.docker.com/layers/mattrayner/lamp/build-210-2004-php8/images/sha256-f7caeba589eaea7e3d20f4ae3e3bf88233e66e7df59eb5adb49161a5365f9f90?context=explore), [`build-210-2004`](https://hub.docker.com/layers/mattrayner/lamp/build-210-2004/images/sha256-f7caeba589eaea7e3d20f4ae3e3bf88233e66e7df59eb5adb49161a5365f9f90?context=explore), [`build-210`](https://hub.docker.com/layers/mattrayner/lamp/build-210/images/sha256-f7caeba589eaea7e3d20f4ae3e3bf88233e66e7df59eb5adb49161a5365f9f90?context=explore), [`latest-2004-php8`](https://hub.docker.com/layers/mattrayner/lamp/latest-2004-php8/images/sha256-f7caeba589eaea7e3d20f4ae3e3bf88233e66e7df59eb5adb49161a5365f9f90?context=explore) and [`latest-2004`](https://hub.docker.com/layers/mattrayner/lamp/latest-2004/images/sha256-f7caeba589eaea7e3d20f4ae3e3bf88233e66e7df59eb5adb49161a5365f9f90?context=explore) are the same digest. I don't know if those images are not working.

> It seems to working now.

Good to hear that.

**Comment by kjlhgfds** [comment]
Well, I actually have the same error again...
What should be my next step ?

**Comment by pzhlkj6612** [comment]
> I entered the container with `docker exec -it blabla /bin/bash` and executed `source /etc/apache2/envvars && apache2` The answer was `httpd (pid 30) already running`

Well, maybe supervisor was constantly trying to launch Apache. Please execute `supervisorctl stop apache2` first, then retry launching Apache manually and see the log.

**Comment by kjlhgfds** [comment]
When I execute `supervisorctl stop apache2` I have `apache2: ERROR (not running)`.
Then when I execute `supervisorctl start apache2` I have `apache2: ERROR (spawn error)`.

**Comment by pzhlkj6612** [comment]
Well, you should execute `source /etc/apache2/envvars && apache2` instead of `supervisorctl start apache2` . The "spawn error" message does not help.

**Comment by pzhlkj6612** [comment]
OK. I get your point. 

```bash
ps -e -o pid,args | grep apache  # to see all Apache processes
killall apache2  # kill all Apache
ps -e -o pid,args | grep apache  # there should be nothing
source /etc/apache2/envvars && apache2  # to see what happen
```

**Comment by kjlhgfds** [comment]
Hey @pzhlkj6612 ,
Sorry for the silence, I totally forgot about this thread :/
I never tried what you suggested cause I finally used another system.
Anyway, thanks for you help :)
