### ISSUE TITLE
MYSQL_PASS variable in Dockerfile contains invalid charter

### ISSUE THREAD

**Issue by kgooris** [mattrayner/docker-lamp#19]
Hi,

I think this line needs to be modified in the dockerfile
ENV MYSQL_PASS:-$(pwgen -s 12 1)

ENV needs to be set with = sign, or am I wrong?

**Comment by mattrayner** [comment]
As far as I know you can use `:` - it works?

If you can find some docs that say you shouldn't / that this is wrong, I'll happily have it change?

**Comment by pzhlkj6612** [comment]
@mattrayner Hi, I found a doc from [ENV # | Docker Documentation](https://docs.docker.com/engine/reference/builder/#env).

> The `ENV` instruction has two forms. The first form, `ENV <key> <value>`, will set a single variable to a value. The entire string after the first space will be treated as the `<value>` - including whitespace characters. The value will be interpreted for other environment variables, so quote characters will be removed if they are not escaped.
> The second form, `ENV <key>=<value> ...`, allows for multiple variables to be set at one time. Notice that the second form uses the equals sign (=) in the syntax, while the first form does not. Like command line parsing, quotes and backslashes can be used to include spaces within values.

<br>

I will show the difference between environment variables list of two version systems.

(1604 is minus and 1804 is plus. Images are all from build-133 9dd205bbfb0bebb84e0b84509813b78cac1b40c6)

(The variable named `BASH_VERSINFO`, `BASH_VERSION` and `HOSTNAME` has been ignored)

`env`:

```
MYSQL_PASS:-$(pwgen=-s 12 1)
```

`export`:

``` diff
- declare -x MYSQL_PASS:-$(pwgen
+ 
```

`set`:

```
MYSQL_PASS* is not here.
```

`MYSQL_PASS` has not been set correctly.

---

At the same time, I found the code in `create_mysql_users.sh` to generate the password for `admin`. But the name of `MYSQL_ADMIN_PASS` does not match `MYSQL_PASS`.

https://github.com/mattrayner/docker-lamp/blob/9dd205bbfb0bebb84e0b84509813b78cac1b40c6/supporting_files/create_mysql_users.sh#L13-L17

It seems that this is indeed a design issue with the Dockerfile.
