### ISSUE TITLE
Trying to restore databases based on mysqldumps fails

### ISSUE THREAD

**Issue by DenLilleMand** [mattrayner/docker-lamp#21]
Hi 

I am simply trying to do a:
` mysql -uroot -p<pass> <dbname> < <some_dump>.sql ` 
Because we're "faking" a whole production environment inside of this docker 
container. Unfortunately, it fails because the mysql service isn't up and running when we execute the scripts. I have both tried to execute it in a 
bash script after i do the docker run on the container, exactly the same way that you use mysql in the documentation. And i get the same error if i e.g. copy all of the *.sql files with COPY or ADD, and then with CMD try to execute them. So it is like that the way sql works with this image is that the service isn't up and running. Have you tried to restore any database via mysql your self? or are you able to provide a recipe? been stuck on this issue for 5 hours or so :(

**Comment by DenLilleMand** [comment]
To provide more of an example. We have these in the Dockerfile:

```
ADD setup_sql.sh /setup_sql.sh
ADD create_schemas.sql /create_schemas.sql
ADD cerafakt.sql /cerafakt.sql
ADD myhouse.sql /myhouse.sql

RUN chmod +x /setup_sql.sh
```

And then through a script:

```
docker build -t myhouse_and_cerafakt .  

docker run -d  -p 8080:8080 -p 50000:50000 -v cera_home:/var/cera --name myhouse myhouse_and_cerafakt

docker exec -u root myhouse /setup_sql.sh
```
We even tried a completely hacked solution, that actually works _sometimes_:
Wait for like 30 seconds. And then manually run:
`docker exec -u root myhouse /setup_sql.sh`

And yes, i think its so weird, that it is only sometimes it works. 

So it was this solution, and then i don't have the code for the other solution i tried but it was basically just "start the mysql service" / "execute the *.sql scripts that we copied over. "

What is the mysql service doing in this container? and how to access it stable?

Thanks a bunch !

**Comment by DenLilleMand** [comment]
This is the specific error message i get:

`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

When executing: 

`docker exec -u root myhouse /setup_sql.sh`

The funny thing is, it actually works if i run it multiple times.

**Comment by mattrayner** [comment]
The delay in MySQL being up and ready for commands would explain why it works after multiple attempts

**Comment by mattrayner** [comment]
I'll close this issue for now, if you have any further questions, feel free to reopen
