### ISSUE TITLE
Edit MySql configuration

### ISSUE THREAD

**Issue by nzurita** [mattrayner/docker-lamp#23]
Trying to edit `/etc/mysql/conf.d/mysql.cnf` or ``/etc/mysql/my.cnf` seems to have no effect in actual server. Even stopping MySql server with `service mysql stop` keeps phpMyAdmin session alive, so I think I'm not working on real mysql server.

What is the correct way to modify mysql config? (I need to disable *NO_ZERO_IN_DATE,NO_ZERO_DATE* and *STRICT* mode)

Thank you

**Comment by grepollo** [comment]
Hi, 

Have you figure out this one? I also need to update some config in mysql.

Thanks.

**Comment by nzurita** [comment]
Not yet, so far I'm setting up the configuration *by hand*, and this needs to be done in every container restart, when I have more some time I'll try to provide the container with some more stable configuration.

I execute this con phpMyAdmin console, and as I sayed, I have to repeat everytime I restart, not very efficient yet but at least a solution:

```
SET @@GLOBAL.sql_mode='IGNORE_SPACE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
```

**Comment by mattrayner** [comment]
You *could* created a local Dockerfile which has an updated config file, referencing my image with your changes? Alternatively, if this is a common thing we could role it into the built-in config?

**Comment by nzurita** [comment]
I'll try to buld this file in a couple of weeks, @mattrayner , thank you

**Comment by cronfy** [comment]
I am trying to do the same

```
FROM mattrayner/lamp:latest-1604

RUN echo 'sql_mode = "NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"' > /etc/mysql/mysql.conf.d/10-legacy.cnf 

CMD ["/run.sh"]
```

But after build there is no `/etc/mysql/mysql.conf.d/10-legacy.cnf `.

What am I doing wrong?

**Comment by mattrayner** [comment]
Sorry I've been really busy at work and not able to look into this, its been a while so I'm going to close this issue but if any of you are still having issues, comment back and I'll re-open.

**Comment by pimvanderheijden** [comment]
I think it's supposed to be this:

```
echo '[mysqld]' >> /etc/mysql/my.cnf;
echo 'sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"' >> /etc/mysql/my.cnf;
```

But the sql_mode is not picked up for me. After `service mysql restart` and `mysql -u root -e "select @@sql_mode"` I still see the `ONLY_FULL_GROUP_BY` I tried to get rid of:
```
+-----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+-----------------------------------------------------------------------------------------------------------------------+
```

Read more here: https://www.sitepoint.com/quick-tip-how-to-permanently-change-sql-mode-in-mysql/

**Comment by spamabi** [comment]
Has anyone achieved to disable strict mode by default?
