### ISSUE TITLE
Lost data

### ISSUE THREAD

**Issue by ElRochito** [mattrayner/docker-lamp#25]
Hi everybody,

I'm starting with the docker. When I launch the container, I create a database and then I stop it.
When I want to run it again, my database is gone.
I can't figure out how to make my data persistent

Thank you in advance

**Comment by juliopedreira** [comment]
By default mysql data is stored in the instance, so when you remove it, all it's data is lost.

If you want to persist it, you have to map a folder to the volume "/var/lib/mysql", as explained in the "[Persisting your MySQL](https://github.com/mattrayner/docker-lamp#persisting-your-mysql)" section of the manual.

To do so, add the follow parameter when running the image: " -v <path>:/var/lib/mysql".

**Comment by mattrayner** [comment]
@ElRochito I hope @juliopedreira's instructions helped, I'm going to close this issue for now but if there are any future issues with this, feel free to re-open
