### ISSUE TITLE
Am I nuts?

### ISSUE THREAD

**Issue by meowsus** [mattrayner/docker-lamp#26]
Or is the PHP version for 16.04 not 5.6.25 (as indicated in the README) but 7.0 instead?

**Comment by mattrayner** [comment]
Hi Curt,
I specifically installed 5.x in the docker image as it was what I needed at
the time - by default, it is 7 though

**Comment by meowsus** [comment]
I guess what I'm saying is, when I log in and run `php -v` it reports 7.0.

**Comment by mattrayner** [comment]
This line should stop that from happening
https://github.com/mattrayner/docker-lamp/blob/master/Dockerfile#L33

Effectively, there are two versions of php running on the image, bit we are specifically setting 5.x as the main one

**Comment by mattrayner** [comment]
@meowsus is this still an issue for you? With the latest image I can confirm I'm seeing:

```
PHP 5.6.37-1+ubuntu16.04.1+deb.sury.org+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

and

```
PHP 5.6.37-1+ubuntu14.04.1+deb.sury.org+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

on 16.04 and 14.04 respectively? If you are still having the issue, feel free to re-open

**Comment by meowsus** [comment]
No. I think that I somehow missed how this was configured. Thanks for the response and this project in general!

**Comment by mattrayner** [comment]
If it helps, I just released a new version of the images which run php7 too 👍
