### ISSUE TITLE
Trying to enable userdir module

### ISSUE THREAD

**Issue by beredim** [mattrayner/docker-lamp#28]
I'm trying to enable the userdir apache module for the container to serve content from the host's /home

So my dockerfile looks like:

```
....
RUN a2enmod userdir
....
VOLUME  ["/etc/mysql", "/var/lib/mysql", "/app", "/home" ]

```

When i run the container, /home gets mounted correctly from the host, but I get 404 when trying to access .../~username/index.html 

EDIT:
So I did a bit more testing:
1. When I try without a /home volume, and I create users inside the container, userdir mod works without issue
2. When I try with an empty host directory  as /home volume, and I create users inside the container, userdir mod works without issue
3. When I try to use host's /home as the container's /home, although it gets mounted correctly, apache returns 404. 

What I want is No. 3.

I don't know how to proceed from here to make this work. My only idea is to implement the same behavior using rewrite instead of userdir.

**Comment by mattrayner** [comment]
@beredim, sorry for the late reply I've been really busy with work 👎 

My first impression would be that this is a permissions issue. Apache needs files to have a public read permission in order to display the file. Do you have an example of the run command you are using?
