### ISSUE TITLE
Run composer as non-root user?

### ISSUE THREAD

**Issue by jonswaff** [mattrayner/docker-lamp#29]
I'm new to using Docker. I'd like to use composer in my PHP project. I see it configured in your Dockerfile. I'm trying to run `composer init` using these commands:

    docker ps
    docker exec CONTAINERID composer init

I receive a message that says "Do not run Composer as root/super user! See https://getcomposer.org/root for details."

Is there an existing user that can be used to execute composer commands? or perhaps I need to create a local Dockerfile that creates a new user and gives that user permission to composer? Advice would be appreciated.

**Comment by mattrayner** [comment]
Hi @jonswaff, I guess, for me, using composer as a root user inside of Docker is. like a mitigated risk. For a number of reasons, this Docker image is set up to run as root.

We could create an additional user etc but as this image is meant for development I didn't see the immediate need.

I'd be happy to review a PR to bring this in though?

**Comment by jonswaff** [comment]
Hi @mattrayner. That makes perfect sense. I think running commands as root for development purposes is fine. I just don't know the correct command to override that warning as I am new to docker. Do you know offhand?

`docker exec CONTAINERID composer init` does not work. Maybe `docker exec CONTAINERID composer init --privileged`?

**Comment by mattrayner** [comment]
Hi @jonswaff,
 Looking at the composer documentation here: https://getcomposer.org/doc/03-cli.md#composer-allow-superuser

I think you'd want something like:

```bash
docker exec CONTAINERID export COMPOSER_ALLOW_SUPERUSER=1
```

Then commands such as 
```bash
docker exec CONTAINERID composer init
```

should function as expected. For single commands you could also try:
```bash
docker exec CONTAINERID export COMPOSER_ALLOW_SUPERUSER=1 composer init
```

**Comment by jonswaff** [comment]
Perfect. Thank you.
