### ISSUE TITLE
Second execution just hangs there

### ISSUE THREAD

**Issue by matyaspeto** [mattrayner/docker-lamp#30]
Hi,

when I first run `docker run -p "80:80" -v ${PWD}/app:/app mattrayner/lamp:latest-1604` on a clean Docker, it works as expected. Containers starts, all good.
Then as I stop the running container with `docker stop` or `docker kill`, then try to run the first command again, it just hangs there and nothing happens.
Meanwhile I can see in `docker ps`, that there is a running container, but none of the services are available.

**Comment by mattrayner** [comment]
I'll try and look into this today and will report back what I find :)

**Comment by mattrayner** [comment]
Hi @matyaspeto I've not been able to re-create this locally, is this still an issue for you?

I'm going to close it for now, but If you have any further issues, feel free to re-open 👍
