### ISSUE TITLE
PHP 7?

### ISSUE THREAD

**Issue by dmahtani** [mattrayner/docker-lamp#31]
Will there be a PHP 7 release of DockerLAMP?

**Comment by mattrayner** [comment]
Hi @dmahtani, there's no reason there can't be - I'll try and take some time today to see what I'd need to do - by default all the images come with PHP7 - I just install 5.* over it

**Comment by shavonn** [comment]
Yes, please!

**Comment by mattrayner** [comment]
@dmahtani & @shavonn I've just merged in #37 which adds php-7 variations of both Ubuntu 14.04 and 16.04. Hopefully this works for you, if not please let me know 👍
