### ISSUE TITLE
MySQL fails to start when mounting local folder on Windows + VirtualBox

### ISSUE THREAD

**Issue by erichmusick** [mattrayner/docker-lamp#32]
I'm using Docker Toolbox for Windows, version Docker version 18.03.0-ce, build 0520e24302. (I'm using this rather than the newer Docker for Windows so I can continue to use VirtualBox.)

When I try to map a local folder for MySQL, it seems MySQL can't start. I see repeated output:

> => Waiting for confirmation of MySQL service startup

In VirtualBox, my whole 'c' drive is shared and configured for "full" access. Other directories map properly (e.g. for Apache), though that is only doing read operations.

Output when trying to run `mysqld`:

> root@cd3f5b3cb152:/var/log/mysql# mysqld
> 180520  1:32:17 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
> 180520  1:32:17 [Note] mysqld (mysqld 5.5.58-0ubuntu0.14.04.1) starting as process 577 ...
> 180520  1:32:17 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
> 180520  1:32:17 [Warning] Using unique option prefix myisam-recover instead of myisam-recover-options is deprecated and will be removed in a future release. Please use the full name instead.
> 180520  1:32:17 [Note] Plugin 'FEDERATED' is disabled.
> 180520  1:32:17 InnoDB: The InnoDB memory heap is disabled
> 180520  1:32:17 InnoDB: Mutexes and rw_locks use GCC atomic builtins
> 180520  1:32:17 InnoDB: Compressed tables use zlib 1.2.8
> 180520  1:32:17 InnoDB: Using Linux native AIO
> 180520  1:32:17 InnoDB: Initializing buffer pool, size = 128.0M
> 180520  1:32:17 InnoDB: Completed initialization of buffer pool
> InnoDB: Error: space header page consists of zero bytes in data file ./ibdata1
> 180520  1:32:17 InnoDB: Could not open or create data files.
> 180520  1:32:17 InnoDB: If you tried to add new data files, and it failed here,
> 180520  1:32:17 InnoDB: you should now edit innodb_data_file_path in my.cnf back
> 180520  1:32:17 InnoDB: to what it was, and remove the new ibdata files InnoDB created
> 180520  1:32:17 InnoDB: in this failed attempt. InnoDB only wrote those files full of
> 180520  1:32:17 InnoDB: zeros, but did not yet use them in any way. But be careful: do not
> 180520  1:32:17 InnoDB: remove old data files which contain your precious data!
> 180520  1:32:17 [ERROR] Plugin 'InnoDB' init function returned error.
> 180520  1:32:17 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
> 180520  1:32:17 [ERROR] Unknown/unsupported storage engine: InnoDB
> 180520  1:32:17 [ERROR] Aborting
> 
> 180520  1:32:17 [Note] mysqld: Shutdown complete

I'm new to Docker, and I'm not a super expert at MySQL ... so I'd appreciate any guidance for how to troubleshoot further. I can see that a bunch of files were created in the `mysql` folder I mounted.

VirtualBox version:  5.2.8 r121009

**Comment by erichmusick** [comment]
I was able to work around this:

1. Created a file with innodb config:

```
[mysqld]
innodb_flush_method=O_DSYNC
innodb-use-native-aio=0
log_bin=ON
```

2. Added file to my DockerFile:

```
ADD files/mysqld_innodb.cnf /etc/mysql/conf.d/mysqld_innodb.cnf
```

Thanks to the pointers at: https://github.com/boot2docker/boot2docker/issues/1300

I'd send a PR, but not sure of the implications for other folks on different configurations.

**Comment by mattrayner** [comment]
Hey Erich, if you open a PR, I’ll add the ‘default’ innodb confit that
people can override on their own?

Thanks,
Matt

**Comment by erichmusick** [comment]
Hey Matt - Sorry ... took some time for me to chase down a couple issues related to the change. Finally sent the PR.

**Comment by mattrayner** [comment]
@erichmusick this should all be merged in and released in the next 15 minutes or so, sorry for the delay work has been really hectic!

**Comment by kuhnwei** [comment]
postgresql  has the same error ...

**Comment by mattrayner** [comment]
@kuhnwei Postgres isn't installed into this image nay default, can you tell me a bit more about your setup?
