### ISSUE TITLE
Dockerfile Connect to database and create table

### ISSUE THREAD

**Issue by laur1s** [mattrayner/docker-lamp#39]
Hi,

I'd like to Create a database and a table when launching this image from a dockerfile. The problem I face is that I don't really know how can I get a mysql password from docker. Is it possible to do that?

**Comment by mattrayner** [comment]
Hi Laurynas,
When the image first boots it creates a random root password. If you use a
volume to persist your data, or take a snapshot of the MySQL folder after
the password has been generated, you can do this. Alternatively, once the
image has booted, I’m pretty sure that you can use root and no password
from within the machine to write to the database?

I hope this helps,
Matt

**Comment by laur1s** [comment]
Hi Matt,

Thanks for the explanation. That solves my problem.
