### ISSUE TITLE
change the default '/app' directory

### ISSUE THREAD

**Issue by kentcc88** [mattrayner/docker-lamp#43]
could tell me how and where to change the '/app' directory to another?

**Comment by mattrayner** [comment]
Hi, changing the /app directory required changing the apache configuration,
and possibly some other bits too, if you don’t mind my asking, why do you
need to change it?

**Comment by kentcc88** [comment]
My website has been installed in '/app' directory successfully base on your "docker-lamp", but my source code needs run in '/app/public'. So now my situation is , when i open my web, need to add '/public' at the end of the domain (http://www.xxx.com/public).

**Comment by mattrayner** [comment]
Not a problem, I’d personally recommend restructuring to remove the public
folder

**Comment by kentcc88** [comment]
alright, but i will try your method first, if it still not works, i will consider to restructure removing 'public' folder.

**Comment by kentcc88** [comment]
i try to build a soft link to '/app/public' so that it works now. This seems to be a relatively simple method.

**Comment by mattrayner** [comment]
I'm glad you managed to get it working, I'll close the issue now but if you have any other questions/problems feel free to open a new one :)

**Comment by rulatir** [comment]
I request reopening this issue. There are applications where the PHP code includes files from above the document root. If the document root is forced to be /app, there is no way to recreate the directory structure expected by the application.
