### ISSUE TITLE
cannot export 3306 ，binding 127.0.0.1:3306 not 0.0.0.0:3306

### ISSUE THREAD

**Issue by ylucifer** [mattrayner/docker-lamp#45]
mattrayner/lamp:latest-1604-php7

**Comment by mattrayner** [comment]
Hi @ylucifer, the latest image versions now support this. Please re-download and try again

**Comment by mattrayner** [comment]
Hi @ylucifer, the latest image version should now support this. Please re-pull and try again.

**Comment by alanchen222** [comment]
@mattrayner I have been suffering this issue for days, and thank you for fixing it.
But, although php5 is end of life, a lot of systems are still running on php5 (like mine), could you please  also fix this issue on mattrayner/lamp:latest-1404-php5 and mattrayner/lamp:latest-1604-php5 ?

**Comment by mattrayner** [comment]
Hi, I’ll take a look at this today and see what I can come up with
