### ISSUE TITLE
No support for custom virtualhost configs

### ISSUE THREAD

**Issue by evitolins** [mattrayner/docker-lamp#46]
In many cases, a LAMP setup will already have an Apache config file that defines service-specific settings.  As I can see, this image forces the usage of a premade config file, with no option to replace it   using the Docker workflows.

Would be ideal to add the ability to define alternative virtualhost configurations.

**Comment by mattrayner** [comment]
Hi @evitolins, how would you like to specify custom configs? You could use a volume on your local version? Or make the image as a BASE for a custom Dockerfile?

**Comment by marshel** [comment]
I think a solution would be a volume with a for example host.conf file that would be included or replace the default.conf apache config file.

**Comment by bartclaeys** [comment]
Just installed this image and also trying to figure out how to configure virtual hosts.

**Comment by mattrayner** [comment]
@evitolins @marshel @bartclaeys I think you could do this using an explicit volume - something like:

```bash
docker run -i -t -p "80:80" -v ${PWD}/default.conf:/etc/apache2/sites-available/000-default.conf -v ${PWD}/app:/app mattrayner/lamp:latest
```

Then if you have a `defult.conf` file with all your virtual hosts in the current directory, that should do it

**Comment by mattrayner** [comment]
Let me know if this worked for any of you - I'm going to close for now but happy to re-open if this is still an issue
