### ISSUE TITLE
[Question] Map container to a custom local host

### ISSUE THREAD

**Issue by edugsdf** [mattrayner/docker-lamp#51]
How do I map the docker container that runs on port 80 to my local machine running on port 80 but using custom host.
Example: 
 * http://site1/   
 * http://site2/

I know I'll have to edit my  `/etc/hosts`

**Comment by souhaiebtar** [comment]
if when you type http://localhost (or http://127.0.0.1) your website open correctly in the browser,

just open /etc/hosts and add
```
127.0.0.1 site1.loc
```

after that just go back to the browser

and type  *http://site1.loc* and it should work
N.B: you can change *site1* *loc* by whatever you want

**Comment by edugsdf** [comment]
> if when you type http://localhost (or http://127.0.0.1) your website open correctly in the browser,
> 
> just open /etc/hosts and add
> 
> ```
> 127.0.0.1 site1.loc
> ```
> after that just go back to the browser
> 
> and type _http://site1.loc_ and it should work
> N.B: you can change _site1_ _loc_ by whatever you want,
> 
> port 80 is the default port for http that is why you dont need to write
> this is not related to docker or container generally

Let me explain better then.

When we run the default command `sudo docker run -i -t -p "80:80" -v ${PWD}/app:/app -v ${PWD}/mysql:/var/lib/mysql mattrayner/lamp:latest-1604-php7`, it creates an image with apache running on port 80 and does map to local port 80. Being accessed by http://localhost/
If I run the same command again, on another terminal, `sudo docker run -i -t -p "81:80" -v ${PWD}/app:/app -v ${PWD}/mysql:/var/lib/mysql mattrayner/lamp:latest-1604-php7` it will create another image pointing to local port 81, I will access this: http://localhost:81/
So far so good.

I want to know how to do a mapping of an X image running on port 80, reply on my custom local host, for example: http://site1/

If it would be to pass another layer for example: `sudo docker run -i -t -p "81:80" -v ${PWD}/app:/app -v ${PWD}/mysql:/var/lib/mysql mattrayner/lamp:latest-1604-php7 --host http://site1/`

My `/etc/hosts` looks like this: 

`127.0.0.1	localhost, site1, site2`

**Comment by edugsdf** [comment]
I was able to find the solution. It was so simple. Sorry for issue.

> sudo docker run **--name "site1"** -i -t -p "80:80" -v ${PWD}/app:/app -v ${PWD}/mysql:/var/lib/mysql mattrayner/lamp:latest-1604-php7
