### ISSUE TITLE
Create ARM version

### ISSUE THREAD

**Issue by ElderTugBoat786** [mattrayner/docker-lamp#55]
It's possible set up this docker image for ARM architecture ( for example for use this in a rpi3b ) ?
Thanks , 
Andrea

**Comment by mattrayner** [comment]
Hi Andrea,
 I am interested in doing this myself - I'm not sure how one goes about creating an ARM variation - I'll have to look into this but it's a solid maybe, depending on my availability.

I've got a child on the way so in December there will be a lot of late nights with nothing to do - perhaps this can be a project for then :)

I'll close off the issue for now, but if I've got any updates in the future I'll be sure to post them back here

Thanks,
Matt

**Comment by pimvanderheijden-cpi** [comment]
Would phusion/baseimage:master-arm work?

**Comment by pimvanderheijden-cpi** [comment]
I guess that won't work for arm64/v8

**Comment by pimvanderheijden-cpi** [comment]
It works!!

We replaced this line https://github.com/mattrayner/docker-lamp/blob/master/2004/Dockerfile#L1 with:
```
FROM phusion/baseimage:latest-arm64
```

Then we ran
```
docker build --build-arg PHP_VERSION=7.4 -t=mattrayner/lamp:latest-2004-php7 -f ./2004/Dockerfile 
```

Then we successfully used that image to run our app on an arm machine :tada:
