### ISSUE TITLE
Fail to build image from Dockerfile

### ISSUE THREAD

**Issue by mJace** [mattrayner/docker-lamp#56]
Branch : Master   
Commit: daef7079c4f082c85d7593c25657d758a5cc01c6  
Docker version : 18.06.1
```
cd docker-lamp/  
docker build -t=mattrayner/lamp:latest-1404 -f ./1404/Dockerfile .  
```
Error  
```
 Step 13/42 : RUN echo exit 0 > /usr/sbin/policy-rc.d &&   LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php &&   apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C &&   apt-get update &&   apt-get -y upgrade &&   apt-get install -y apache2-mpm-prefork &&   a2dismod mpm_prefork &&   a2dismod mpm_event &&   apt-get -y install supervisor wget git apache2 php-xdebug libapache2-mod-php mysql-server php-mysql pwgen php-apcu php7.1-mcrypt php-gd php-xml php-mbstring php-gettext zip unzip php-zip curl php-curl &&   apt-get -y autoremove &&   echo "ServerName localhost" >> /etc/apache2/apache2.conf
 ---> Running in 712a5ea47bed
Cannot add PPA: 'ppa:ondrej/php'.
Please check that the PPA name or format is correct.
The command '/bin/sh -c echo exit 0 > /usr/sbin/policy-rc.d &&   LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php &&   apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C &&   apt-get update &&   apt-get -y upgrade &&   apt-get install -y apache2-mpm-prefork &&   a2dismod mpm_prefork &&   a2dismod mpm_event &&   apt-get -y install supervisor wget git apache2 php-xdebug libapache2-mod-php mysql-server php-mysql pwgen php-apcu php7.1-mcrypt php-gd php-xml php-mbstring php-gettext zip unzip php-zip curl php-curl &&   apt-get -y autoremove &&   echo "ServerName localhost" >> /etc/apache2/apache2.conf' returned a non-zero code: 1
```

**Comment by mattrayner** [comment]
Hi, sorry about the delay - I've been really busy at work - I'll take a look at this now

**Comment by mattrayner** [comment]
Hi @mJace I can't seem to recreate this locally using the command you provided - can you try again with the latest docker files from master and let me know if you are still having issues?

Thanks,
Matt

**Comment by mJace** [comment]
I'm still having this issues.
Tested on Ubuntu 18.04 with docker 18.06.1-ce
docker-lamp at master branch commit 2ab87be Fix spelling error in circle ci config
I tried to build based on 3 Dockerfile, 14,16,18. And all failed for same reason.

Log for build 18.04 version 
```
Step 13/42 : RUN add-apt-repository -y ppa:ondrej/php &&   apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C &&   apt-get update &&   apt-get -y upgrade &&   apt-get -y install supervisor wget git apache2 php-xdebug libapache2-mod-php mysql-server php-mysql pwgen php-apcu php7.1-mcrypt php-gd php-xml php-mbstring php-gettext zip unzip php-zip curl php-curl &&   apt-get -y autoremove &&   echo "ServerName localhost" >> /etc/apache2/apache2.conf
 ---> Running in d56bfb62f0f5
Cannot add PPA: 'ppa:~ondrej/ubuntu/php'.
ERROR: '~ondrej' user or team does not exist.
```

Log for building 16.04 version
```
Step 13/42 : RUN add-apt-repository -y ppa:ondrej/php &&   apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C &&   apt-get update &&   apt-get -y upgrade &&   apt-get -y install supervisor wget git apache2 php-xdebug libapache2-mod-php mysql-server php-mysql pwgen php-apcu php7.1-mcrypt php-gd php-xml php-mbstring php-gettext zip unzip php-zip curl php-curl &&   apt-get -y autoremove &&   echo "ServerName localhost" >> /etc/apache2/apache2.conf
 ---> Running in be2125933a84
Cannot add PPA: 'ppa:~ondrej/ubuntu/php'.
ERROR: '~ondrej' user or team does not exist.
```

Log for building 14.04 version
```
Step 13/42 : RUN echo exit 0 > /usr/sbin/policy-rc.d &&   LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php &&   apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4F4EA0AAE5267A6C &&   apt-get update &&   apt-get -y upgrade &&   apt-get install -y apache2-mpm-prefork &&   a2dismod mpm_prefork &&   a2dismod mpm_event &&   apt-get -y install supervisor wget git apache2 php-xdebug libapache2-mod-php mysql-server php-mysql pwgen php-apcu php7.1-mcrypt php-gd php-xml php-mbstring php-gettext zip unzip php-zip curl php-curl &&   apt-get -y autoremove &&   echo "ServerName localhost" >> /etc/apache2/apache2.conf
 ---> Running in 4464e2e8c95e
Cannot add PPA: 'ppa:ondrej/php'.
Please check that the PPA name or format is correct.
```

**Comment by pzhlkj6612** [comment]
Try this: [Cannot add PPA. Please check that the PPA name or format is correct - Ask Ubuntu](https://askubuntu.com/questions/429803/cannot-add-ppa-please-check-that-the-ppa-name-or-format-is-correct)

<br>

In addition, the tilde in ```~ondrej``` seems to be caused by an encoding issue.

```
WARNING: add-apt-repository is broken with non-UTF-8 locales, see
https://github.com/oerdnj/deb.sury.org/issues/56 for workaround:

# LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
```

**Comment by mattrayner** [comment]
I'm not getting the error adding locally, but it can't find the php libraries so it mush be having problems
I'll dig into this and let you know what I find

**Comment by mattrayner** [comment]
Okay, I can get 1604 and 1804 working locally - it looks like 1404 is out of standard support so I'm making the decision to stop updating the 1404 branch

I don't have the time to keep maintaining it long term and it seems the PHP7 packages have issues

**Comment by mattrayner** [comment]
@mJace do you specifically have a need for 1404? OR were you trying to build all of the images and getting issues with 1404

**Comment by mJace** [comment]
> Okay, I can get 1604 and 1804 working locally - it looks like 1404 is out of standard support so I'm making the decision to stop updating the 1404 branch
> 
> I don't have the time to keep maintaining it long term and it seems the PHP7 packages have issues

> @mJace do you specifically have a need for 1404? OR were you trying to build all of the images and getting issues with 1404

That's okay. I don't have specific needs for 1404.  
Also,the @pzhlkj6612 's solution works, I can build 1604 and 1804 locally now.

**Comment by mattrayner** [comment]
I've pushed new code to master that I can get to build with `make test` - let me know if you are still seeing issues after a new master pull

Sorry for the delay in getting this sorted
