### ISSUE TITLE
[suggestion] A version of this for Nginx

### ISSUE THREAD

**Issue by edugsdf** [mattrayner/docker-lamp#61]
I really like this version of it, I always use it for my local projects.
I do not know if it would be in your interest to create a version for nginx.

I even tried to create a version used nginx + PHP-FPM + xdebug but I could not, because I did not have so much technical knowledge.

do you suggest me some tutorial for me to make a version of this just for nginx? :-)

**Comment by mattrayner** [comment]
Hi @edugsdf,
 Thanks for your message - unfortunately I don't have any plans for an NGINX variation of this image. However, there are a number of images on Docker Hub that may be suitable? Maybe this: https://hub.docker.com/r/webdevops/php-nginx/

Thanks,
Matt
