### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by fabman** [mattrayner/docker-lamp#62]
With docker for windows I try to run any of the versions with:

`docker run -p 80:80 -p 3306:3306 -v D:\dev\docker\www:/app -v D:\dev\docker\mysql:/var/lib/mysql mattrayner/lamp:latest`

and any version get stuck on:
`sed: can't read /etc/php/7.2/apache2/php.ini: No such file or directory`

And take forever to start the container. After almost five minutes continues and starts the container.

**Comment by souhaiebtar** [comment]
@fabman try to integrate docker for windows in wsl and re run the commands from inside wsl, 
check this [link](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly)

**Comment by mattrayner** [comment]
@fabman I'm really sorry but that seems to be a Windows specific issue - unfortunately I don't have access to a windows machine to attempt to bug fix - let me know if you are still experiencing this and I'll try what I can

**Comment by Naahuel** [comment]
I'm on Linux and I have the same issue. I gave it a little time and it took off. It works great, it just takes *ages* to boot. I'm new to docker and maybe I'm missing something stupid. Just thought I'd share this with @fabman. Give it some time and it should start (at least id did for me)

![](https://i.imgur.com/THa48T8.png)

**Comment by suryaspl** [comment]
Hi, I have the same problem on mac. Here is my screenshoot.

![image](https://user-images.githubusercontent.com/45868605/66542120-db946e80-eb5b-11e9-8e35-070626c44040.png)

Yes apache is running but volume not integrated. So if I visit http://localhost:6680 then it show blank list directory.

In my first attempt it work fine, but I dont know why this error in second attempt.

Where I'm doing wrong? How I can debug?

Thanks in advance.
