### ISSUE TITLE
Connecting to MySQL remotely

### ISSUE THREAD

**Issue by otrsw** [mattrayner/docker-lamp#63]
I am struggling to enable remote connection to the mysql server.

1. MySQL running fine and I can access using the admin user via phpMyAdmin
2. The rights for admin seem to allow all hosts (%)
3. When trying to connect from another PC via MySQL IDE I always get 10061:Unknown error

I created the docker container with a port mapping "xxxx:3306" - so I am using the external port in my connection setup.

Do I need to do anything else to allow external connection?

**Comment by pzhlkj6612** [comment]
I also encountered the same issue and found a temporary solution.

This is the content at the end of `/var/log/mysql/error.log`.

``` log
2019-06-05T14:03:33.303057Z 0 [Note] Server hostname (bind-address): '127.0.0.1'; port: 3306
2019-06-05T14:03:33.303101Z 0 [Note]   - '127.0.0.1' resolves to '127.0.0.1';
2019-06-05T14:03:33.303186Z 0 [Note] Server socket created on IP: '127.0.0.1'.
...
```

`127.0.0.1` has been bound. Let's find its location.

``` console
$ grep -rwn /etc/ -e 'bind-address'
/etc/mysql/mysql.conf.d/mysqld.cnf:43:bind-address              = 127.0.0.1
/etc/mysql/conf.d/mysqld_innodb.cnf:6:bind-address=0.0.0.0
```

In `/etc/mysql/mysql.conf.d/mysqld.cnf`, change the value of `bind-address` to `0.0.0.0`, or comment this line out directly.

Then, restart mysql by `/etc/init.d/mysql restart`. Read the log file mentioned above.

``` log
2019-06-05T14:27:05.967013Z 0 [Note] Server hostname (bind-address): '0.0.0.0'; port: 3306
2019-06-05T14:27:05.967085Z 0 [Note]   - '0.0.0.0' resolves to '0.0.0.0';
2019-06-05T14:27:05.967176Z 0 [Note] Server socket created on IP: '0.0.0.0'.
...
```

It works.

Ref: [linux - How to bind MySQL server to more than one IP address? - Server Fault](https://serverfault.com/questions/139323/how-to-bind-mysql-server-to-more-than-one-ip-address)

---

The file `/etc/mysql/conf.d/mysqld_innodb.cnf` seems useless, isn't it?

**Comment by pzhlkj6612** [comment]
> Then, restart mysql by `/etc/init.d/mysql restart`. Read the log file mentioned above.

It's worth noting that if I execute this command, the process of stopping mysql service always return `fail`.

``` console
$ /etc/init.d/mysql restart
 * Stopping MySQL database server mysqld   [fail]
 * Starting MySQL database server mysqld   [ OK ]
$ /etc/init.d/mysql status
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'debian-sys-maint'@'localhost' (using password: YES)'
 *
```

To fix it, I searched the Internet and got a solution. Find out the password of `debian-sys-maint` from `/etc/mysql/debian.cnf`, and log in MySQL as `admin`, then execute the sql:

``` sql
GRANT ALL PRIVILEGES ON *.* TO 'debian-sys-maint'@'localhost' IDENTIFIED BY '*the password I found*';
```

Go back to shell, and try restarting MySQL.

``` console
 /etc/init.d/mysql restart
 * Stopping MySQL database server mysqld   [ OK ]
 * Starting MySQL database server mysqld   No directory, logging in with HOME=/   [ OK ]
```

Issue solved.

<br>

You can follow links below to learn more.

Ref 1: [Why can’t I stop the MySQL service on Debian? - Super User](https://superuser.com/questions/268053/why-can-t-i-stop-the-mysql-service-on-debian)

Ref 2: [linux - What is the debian-sys-maint MySQL user (and more)? - Server Fault](https://serverfault.com/questions/9948/what-is-the-debian-sys-maint-mysql-user-and-more)

**Comment by freeyland** [comment]
thanx!

**Comment by mattrayner** [comment]
I'm going to take a look at this over the next few days and see if I can fix it in the image

**Comment by mattrayner** [comment]
This should now be fixed in the latest release

Thanks for all your patience, if you can confirm and post back that would be amazing!
