### ISSUE TITLE
Remove VOLUME "/etc/mysql"

### ISSUE THREAD

**Issue by pzhlkj6612** [mattrayner/docker-lamp#70]
There is a volume point to `/etc/mysql' in each Dockerfile.

https://github.com/mattrayner/docker-lamp/blob/9dd205bbfb0bebb84e0b84509813b78cac1b40c6/1604/Dockerfile#L89

https://github.com/mattrayner/docker-lamp/blob/9dd205bbfb0bebb84e0b84509813b78cac1b40c6/1804/Dockerfile#L89

The user can mount a folder to volume `/etc/mysql`. If the configuration files in this folder are correct, it will work well. But if it's an empty folder, or the files are corrupted, then `mysqld` will not work as expected.

After testing, I found it difficult to rebuild configuration files in `/etc/mysql`. If a user want to use his own config, he can use `docker cp` command to achieve this goal. So I don't think there should be the `VOLUME "/etc/mysql"` in Dockerfiles. In other words, this folder needs to be protected.

---

If `/etc/mysql` has not been *volumed*, some commands in `run.sh` should be moved to Dockerfiles as persisted configuration. So, the boot script only needs to check some essential configurations but does not include `bind-address` - it will be modified by the user.

---

The rebuilding of `/var/lib/mysql` is easier. Both `dpkg-reconfigure` and `mysqld --initialize` (`mysqld --initialize-insecure`) can do it. The new mysql test script is being written.

**Comment by mattrayner** [comment]
Hi @pzhlkj6612, This is great, thanks for raising, I'll make the change locally now and test - I'll also look at adding additional sections to the README file that covers the `docker cp` usage

**Comment by mattrayner** [comment]
I’ve removed the volume 😊
