### ISSUE TITLE
I need phpize, how to install?

### ISSUE THREAD

**Issue by gko1943** [mattrayner/docker-lamp#71]
I need the phpize to install oci8 , but when i "apt-get install php5-dev", the php version is

**Comment by pzhlkj6612** [comment]
This image is using PHP 7. Just try `apt-get install php7.3-dev` in the container.

**Comment by gko1943** [comment]
> This image is using PHP 7.3. Just try `apt-get install php7.3-dev` in the container.

I was use php5.6, after apt install pohp5-dev, the php version is changed to 7.2.9, my application not work...

**Comment by pzhlkj6612** [comment]
OK, you may have to use an older version of images, such as `mattrayner/lamp:latest-1604` and `mattrayner/lamp:latest-1404`. Then install `php5.6-dev`.

**Comment by pzhlkj6612** [comment]
I'm sorry for my mistake, you should use `mattrayner/lamp:latest-1604-php5` or `mattrayner/lamp:latest-1404-php5`.

**Comment by pzhlkj6612** [comment]
I got your point.

```console
$ ls -l /usr/bin/ | grep php
-rwxr-xr-x 1 root root        3080 Apr  5  2016 dh_phpcomposer
-rwxr-xr-x 1 root root        5486 Apr  5  2016 dh_phppear
lrwxrwxrwx 1 root root          21 Aug 21  2018 php -> /etc/alternatives/php
-rwxr-xr-x 1 root root     4488224 May 31 12:49 php5.6
-rwxr-xr-x 1 root root     4875488 Aug 19  2018 php7.2
lrwxrwxrwx 1 root root          28 Jul 16 14:23 php-config -> /etc/alternatives/php-config
-rwxr-xr-x 1 root root        4395 May 31 12:48 php-config5.6
lrwxrwxrwx 1 root root          24 Jul 16 14:23 phpize -> /etc/alternatives/phpize
-rwxr-xr-x 1 root root        4746 May 31 12:48 phpize5.6
```

```console
$ ls -l /etc/alternatives/ | grep php
lrwxrwxrwx 1 root root  21 Aug 21  2018 libphp7 -> /usr/lib/libphp7.2.so
lrwxrwxrwx 1 root root  15 Jul 16 14:23 php -> /usr/bin/php7.2
lrwxrwxrwx 1 root root  31 Jul 16 14:23 php.1.gz -> /usr/share/man/man1/php7.2.1.gz
lrwxrwxrwx 1 root root  22 Jul 16 14:23 php-config -> /usr/bin/php-config5.6
lrwxrwxrwx 1 root root  38 Jul 16 14:23 php-config.1.gz -> /usr/share/man/man1/php-config5.6.1.gz
lrwxrwxrwx 1 root root  18 Jul 16 14:23 phpize -> /usr/bin/phpize5.6
lrwxrwxrwx 1 root root  34 Jul 16 14:23 phpize.1.gz -> /usr/share/man/man1/phpize5.6.1.gz
```

```console
$ update-alternatives --set php /usr/bin/php5.6

$ ls -l /etc/alternatives/ | grep php
lrwxrwxrwx 1 root root  21 Aug 21  2018 libphp7 -> /usr/lib/libphp7.2.so
lrwxrwxrwx 1 root root  15 Jul 16 14:24 php -> /usr/bin/php5.6
lrwxrwxrwx 1 root root  31 Jul 16 14:24 php.1.gz -> /usr/share/man/man1/php5.6.1.gz
lrwxrwxrwx 1 root root  22 Jul 16 14:23 php-config -> /usr/bin/php-config5.6
lrwxrwxrwx 1 root root  38 Jul 16 14:23 php-config.1.gz -> /usr/share/man/man1/php-config5.6.1.gz
lrwxrwxrwx 1 root root  18 Jul 16 14:23 phpize -> /usr/bin/phpize5.6
lrwxrwxrwx 1 root root  34 Jul 16 14:23 phpize.1.gz -> /usr/share/man/man1/phpize5.6.1.gz
```

```diff
- lrwxrwxrwx 1 root root  15 Jul 16 14:23 php -> /usr/bin/php7.2
+ lrwxrwxrwx 1 root root  15 Jul 16 14:24 php -> /usr/bin/php5.6
- lrwxrwxrwx 1 root root  31 Jul 16 14:23 php.1.gz -> /usr/share/man/man1/php7.2.1.gz
+ lrwxrwxrwx 1 root root  31 Jul 16 14:24 php.1.gz -> /usr/share/man/man1/php5.6.1.gz
```

It's noticeable that when `/etc/alternatives/php` points to `/usr/bin/php7.2`, `php-config` and `phpize` still point to the components of php 5.6.

<br>

Ref:

[6. Changing PHP version # Working with multiple versions of PHP 7.3, 7.2, 7.1, 7.0 &amp; 5.6 on Ubuntu](https://www.atyantik.com/working-with-multiple-versions-of-php-7-3-7-2-7-1-7-0-5-6-on-ubuntu/#mce_3)

**Comment by gko1943** [comment]
> I got your point.
> 
> ```
> $ ls -l /usr/bin/ | grep php
> -rwxr-xr-x 1 root root        3080 Apr  5  2016 dh_phpcomposer
> -rwxr-xr-x 1 root root        5486 Apr  5  2016 dh_phppear
> lrwxrwxrwx 1 root root          21 Aug 21  2018 php -> /etc/alternatives/php
> -rwxr-xr-x 1 root root     4488224 May 31 12:49 php5.6
> -rwxr-xr-x 1 root root     4875488 Aug 19  2018 php7.2
> lrwxrwxrwx 1 root root          28 Jul 16 14:23 php-config -> /etc/alternatives/php-config
> -rwxr-xr-x 1 root root        4395 May 31 12:48 php-config5.6
> lrwxrwxrwx 1 root root          24 Jul 16 14:23 phpize -> /etc/alternatives/phpize
> -rwxr-xr-x 1 root root        4746 May 31 12:48 phpize5.6
> ```
> 
> ```
> $ ls -l /etc/alternatives/ | grep php
> lrwxrwxrwx 1 root root  21 Aug 21  2018 libphp7 -> /usr/lib/libphp7.2.so
> lrwxrwxrwx 1 root root  15 Jul 16 14:23 php -> /usr/bin/php7.2
> lrwxrwxrwx 1 root root  31 Jul 16 14:23 php.1.gz -> /usr/share/man/man1/php7.2.1.gz
> lrwxrwxrwx 1 root root  22 Jul 16 14:23 php-config -> /usr/bin/php-config5.6
> lrwxrwxrwx 1 root root  38 Jul 16 14:23 php-config.1.gz -> /usr/share/man/man1/php-config5.6.1.gz
> lrwxrwxrwx 1 root root  18 Jul 16 14:23 phpize -> /usr/bin/phpize5.6
> lrwxrwxrwx 1 root root  34 Jul 16 14:23 phpize.1.gz -> /usr/share/man/man1/phpize5.6.1.gz
> ```
> 
> ```
> $ update-alternatives --set php /usr/bin/php5.6
> 
> $ ls -l /etc/alternatives/ | grep php
> lrwxrwxrwx 1 root root  21 Aug 21  2018 libphp7 -> /usr/lib/libphp7.2.so
> lrwxrwxrwx 1 root root  15 Jul 16 14:24 php -> /usr/bin/php5.6
> lrwxrwxrwx 1 root root  31 Jul 16 14:24 php.1.gz -> /usr/share/man/man1/php5.6.1.gz
> lrwxrwxrwx 1 root root  22 Jul 16 14:23 php-config -> /usr/bin/php-config5.6
> lrwxrwxrwx 1 root root  38 Jul 16 14:23 php-config.1.gz -> /usr/share/man/man1/php-config5.6.1.gz
> lrwxrwxrwx 1 root root  18 Jul 16 14:23 phpize -> /usr/bin/phpize5.6
> lrwxrwxrwx 1 root root  34 Jul 16 14:23 phpize.1.gz -> /usr/share/man/man1/phpize5.6.1.gz
> ```
> 
> ```diff
> - lrwxrwxrwx 1 root root  15 Jul 16 14:23 php -> /usr/bin/php7.2
> + lrwxrwxrwx 1 root root  15 Jul 16 14:24 php -> /usr/bin/php5.6
> - lrwxrwxrwx 1 root root  31 Jul 16 14:23 php.1.gz -> /usr/share/man/man1/php7.2.1.gz
> + lrwxrwxrwx 1 root root  31 Jul 16 14:24 php.1.gz -> /usr/share/man/man1/php5.6.1.gz
> ```
> 
> It's noticeable that when `/etc/alternatives/php` points to `/usr/bin/php7.2`, `php-config` and `phpize` still point to the components of php 5.6.
> 
> Ref:
> 
> [6. Changing PHP version # Working with multiple versions of PHP 7.3, 7.2, 7.1, 7.0 & 5.6 on Ubuntu](https://www.atyantik.com/working-with-multiple-versions-of-php-7-3-7-2-7-1-7-0-5-6-on-ubuntu/#mce_3)
