### ISSUE TITLE
How to run it correctly so as not to lose the data mysql

### ISSUE THREAD

**Issue by ivonin85** [mattrayner/docker-lamp#72]
I moved the container to a new server. How to run it correctly so as not to lose the data mysql

**Comment by pzhlkj6612** [comment]
Your MySQL table data is saved in `/var/lib/mysql/mysql`.

When you start the container, the script `run.sh` (CMD entry point) will be fired up. It will check whether the folder `/var/lib/mysql/mysql` is exists. If so, the script will NOT do any **deletion** or **modfication** with the files and subfolders in `/var/lib/mysql/mysql`.

https://github.com/mattrayner/docker-lamp/blob/9dd205bbfb0bebb84e0b84509813b78cac1b40c6/supporting_files/run.sh#L48

Every time the container is started, it will do the same checks, so don't worry. But you should back up your files (`/var/lib/mysql`, the entire parent folder) in advance.

Don't forget to do some tests firstly. 

<br>

If you think it's unreliable, use `mysqldump` to export the data from old environment.

A useful question about MySQL data migration: https://askubuntu.com/questions/964417/is-it-possible-to-restore-a-mysql-database-from-the-var-lib-mysql-database-fold

**Comment by mattrayner** [comment]
@pzhlkj6612 thanks for dropping a reply, I'm happy that this is a comprehensive answer so I'm going to close - @ivonin85 if you have any further questions, feel free to drop another reply
