### ISSUE TITLE
/var/log and sed errors in run.sh when running 1804

### ISSUE THREAD

**Issue by rmdave** [mattrayner/docker-lamp#89]
MySQL would not start up.

1. Had to add:

`chown -R www-data:staff /var/log/mysql`

to handle cannot write to dir error.

2. Sed was missing "s/" on line 77:

`sed -i "s/user.*/user = www-data/" /etc/mysql/mysql.conf.d/mysqld.cnf`

Started up, phpmyadmin good...thanks for doing this!  It will help my interns!

**Comment by mattrayner** [comment]
Thanks for the spot, I've implemented a fix and will release a few new images tomorrow with this rolled in

**Comment by mattrayner** [comment]
@rmdave I've just pushed a new release of the image with your fixes included :) Thanks again for contributing
