### ISSUE TITLE
Silly question---command line mode

### ISSUE THREAD

**Issue by mit10000** [mattrayner/docker-lamp#91]
Thanks for sharing.

After run the image with tag latest-1604, the state directly go to apache2 entered RUNNING state, how can I enter command line mode thus I can input some commands?

**Comment by pzhlkj6612** [comment]
@mit10000 
You also need [`run -d ...`](https://docs.docker.com/engine/reference/run/#detached--d) to run the container in background, otherwise you cannot type in any commands.

**Comment by mit10000** [comment]
Thanks @mahmoudajawad @pzhlkj6612. Problem solved.
