### ISSUE TITLE
Rearding mysql directory ! 

### ISSUE THREAD

**Issue by karniv0re-cyber** [mattrayner/docker-lamp#98]
Im am building the project using your Dockerfile. The issue is, initially MYSQL directory does not exists. After running the image, MYSQL directory is made and all the required files are installed. When a new database is created, it gets reflected in the MYSQL directory and works as charm. 

ISSUE: 
But when the project is pushed to Docker Hub and somebody pulls to use it, contents of MYSQL directory are not copied in /var/lib/mysql. Hence the web app doesn't work. 

PS: I first upload the project on GitHub, then I tag the repository to Docker Hub and Docker Hub auto builds the docker using the Dockefile. 

Please suggest me any solution for this.

**Comment by pzhlkj6612** [comment]
Hi. Please see the ["Persisting your MySQL" section](https://github.com/mattrayner/docker-lamp#persisting-your-mysql) in Readme.

**Comment by pzhlkj6612** [comment]
OK, I got your point. Please see the discussions in [Docker commit should retain container data in volumes too](https://forums.docker.com/t/docker-commit-should-retain-container-data-in-volumes-too/28844) and [Commit content of mounted volumes as well](https://stackoverflow.com/questions/46349071/commit-content-of-mounted-volumes-as-well).

> The commit operation will not include any data contained in volumes mounted inside the container.
> *from: https://docs.docker.com/engine/reference/commandline/commit/*

IMO, maybe you should manually store and compress your data outside the container and send it to others.

**Comment by mattrayner** [comment]
Hi @karniv0re-cyber I have to agree with @pzhlkj6612 here, volumes are inherently external to the container so should be sent seperately

**Comment by smalldragoon** [comment]
HI, thanks @pzhlkj6612  for pointing me to this thread.
Idea on my side is that I have used "main" docker image to build a demo server, that I want now to share with other, as simple as possible, as the users are not technical at all ( running a docker will already be a challenge ;-) ). 
So I would need a docker image with all content embeded ( ie : including the DB and the website files ).

**Comment by freakpants** [comment]
@smalldragoon If I understand you correctly, you want to deliver the same code and database everytime, and users won't be developing on this server? I think you could add the files in your Dockerfile when building the image, and not connect the respective directories as volumes when running the image. I think this is a bit antithetical to how docker works, and might not work at all, but you could try it.

**Comment by smalldragoon** [comment]
@freakpants yes, . I did this, removed the link to /app and installed my files and mysql in /var/www/html.
I know and agree that in is antiethical on how docker works, but it will save me hours of support and debugging :P
